################################################
#                                              #
#  Model:                                      #
#  Author: vbadenas                            #
#                                              #
################################################

# seeds
seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]
experiment_name: pets_vgg11_same
experiment_folder: "results/"
device: "cuda:0"

# data folder
data_folder: "./data/"

# training parameters
epochs: 2
batch_size: 32
shuffle: True

num_classes: 37

transform_tensor: !new:torchvision.transforms.ToTensor
transform_random_resized_crop: !new:torchvision.transforms.RandomResizedCrop
    size: 224
transform_resize: !new:torchvision.transforms.Resize
    size: [224, 224]

transform_train: !new:torchvision.transforms.Compose
    transforms: [
        !ref <transform_resize>,
        !ref <transform_tensor>,
        # !ref <transform_normalize>,
    ]

transform_valid: !new:torchvision.transforms.Compose
    transforms: [
        !ref <transform_resize>,
        !ref <transform_tensor>,
        # !ref <transform_normalize>,
    ]

train_dataset: !new:frarch.datasets.oxford_pets.OxfordPets
    subset: train
    transform: !ref <transform_train>

valid_dataset: !new:frarch.datasets.oxford_pets.OxfordPets
    subset: valid
    transform: !ref <transform_valid>

# dataloader options
dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: !ref <shuffle>
    num_workers: 16

opt_class: !name:torch.optim.SGD
    lr: 0.01
    weight_decay: 0.000001
    momentum: 0.9

loss: !new:torch.nn.CrossEntropyLoss

metrics: !new:frarch.modules.metrics.MetricsWrapper
    classification_error: !new:frarch.modules.metrics.ClassificationError

model: !apply:torchvision.models.vgg11
    pretrained: False
    num_classes: !ref <num_classes>

modules:
    model: !ref <model>

checkpointer: !new:frarch.modules.checkpointer.Checkpointer
    save_path: !ref <experiment_folder>
    reference_metric: "classification_error"
    save_best_only: True
    modules:
        model: !ref <model>
