################################################
#                                              #
#  Model:                                      #
#  Author: vbadenas (victor.badenas@gmail.com) #
#                                              #
################################################

# seeds
seed: 42
__set_seed: !apply:torch.manual_seed [!ref <seed>]
experiment_name: "places365_vgg11"
experiment_folder: "results/"
device: "cuda:0"

# data folder
data_folder: ./data/

# training parameters
epochs: 2
batch_size: 16
shuffle: True

num_classes: 365

transform_tensor: !new:torchvision.transforms.ToTensor
transform_resize: !new:torchvision.transforms.Resize
    size: [224, 224]

preprocessing: !new:torchvision.transforms.Compose
    transforms: [
        !ref <transform_resize>,
        !ref <transform_tensor>,
    ]

# dataset object
train_dataset: !new:torchvision.datasets.Places365
    root: !ref <data_folder>
    split: 'train-standard'
    small: true
    download: true
    transform: !ref <preprocessing>

valid_dataset: !new:torchvision.datasets.Places365
    root: !ref <data_folder>
    split: 'val'
    small: true
    download: true
    transform: !ref <preprocessing>

# dataloader options
dataloader_options:
    batch_size: !ref <batch_size>
    shuffle: !ref <shuffle>
    num_workers: 16

opt_class: !name:torch.optim.Adam
    lr: 0.0002

loss: !new:torch.nn.CrossEntropyLoss

metrics: !new:frarch.modules.metrics.MetricsWrapper
    classification_error: !new:frarch.modules.metrics.ClassificationError

model: !apply:torchvision.models.vgg11
    num_classes: !ref <num_classes>
    pretrained: false

modules:
    model: !ref <model>

checkpointer: !new:frarch.modules.checkpointer.Checkpointer
    save_path: !ref <experiment_folder>
    reference_metric: "classification_error"
    modules:
        model: !ref <model>
