name: docs

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master


jobs:
  docs-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Build HTML docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install .[docs]"
#        build-command: "make -C docs html"

    - name: Determine default branch
      run: |
        DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
        echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_ENV
        echo "default_branch_ref=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == env.default_branch_ref
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "docs/_build/html/"

  # docs-pdf:
  #   if: |
  #     github.event_name == 'pull_request' ||
  #     startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Build PDF docs
  #     uses: ammaraskar/sphinx-action@master
  #     with:
  #       docs-folder: "docs/"
  #       pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
  #       build-command: "make latexpdf"

  #   - uses: actions/upload-artifact@v2
  #     if: startsWith(github.ref, 'refs/tags')
  #     with:
  #       name: Documentation
  #       path: docs/_build/latex/*.pdf
