name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: setup package
      run: |
        python -m pip install .

  unittest:
    strategy:
      matrix:
        python: [3.8, 3.9]
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: install
      run: |
        python -m pip install -q .[test]

    - name: test
      run: |
        coverage run -m unittest discover -s tests/unit
        coverage report -m --omit='tests/unit/*'

    - if: ${{ matrix.python == '3.9' }}
      name: Get Coverage for badge
      run: |
        coverage json
        COVERAGE=$(LC_NUMERIC="en_US.UTF-8" printf "%.2f%%" $(cat coverage.json | jq .totals.percent_covered))
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        REF=${{ github.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        echo $BRANCH_NAME
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

    - if: ${{ matrix.python == '3.9' }}
      name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 9b54bd086e121233d2ad9a62d2136258
        filename: frarch__${{ env.BRANCH }}.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        color: green
        namedLogo: codecov

  unittest-cross-platform:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: install
      run: |
        python -m pip install -q .[test]

    - name: test
      run: |
        coverage run -m unittest discover -s tests/unit
        coverage report -m --omit='tests/unit/*'

  functional:
    strategy:
      matrix:
        python: [3.8, 3.9]
    runs-on: ubuntu-latest
    needs: [build, unittest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: install
      run: |
        python -m pip install -q .[test]
    - name: functional-test
      run: |
        cd tests/functional
        ./runFunctionalTests.sh

  package-and-release:
    runs-on: ubuntu-latest
    needs: [build, unittest, functional]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: install
      run: |
        python -m pip install twine build
        python -m build .

    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
